<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->name }}</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #4e73df; padding-bottom: 10px; }
        .header h1 { color: #4e73df; margin: 0 0 5px 0; font-size: 24px; }
        .header p { margin: 0; color: #666; font-size: 14px; }
        .meta { margin-bottom: 20px; font-size: 11px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f8f9fc; color: #4e73df; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { text-align: center; margin-top: 50px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        .status-badge { padding: 3px 6px; border-radius: 3px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
        .breached-yes { color: red; font-weight: bold; }
        .breached-no { color: green; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>ETMS - {{ $report->name }}</h1>
        <p>SLA Compliance Report</p>
    </div>

    <div class="meta">
        <strong>Generated By:</strong> {{ $report->generatedBy?->name ?? 'System' }}<br>
        <strong>Generated On:</strong> {{ $report->created_at ? $report->created_at->format('M d, Y H:i:s') : now()->format('M d, Y H:i:s') }}<br>
        @if(!empty($report->filters['date_from']))
            <strong>Date Range:</strong> {{ $report->filters['date_from'] }} to {{ $report->filters['date_to'] ?? 'Now' }}
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>Reference #</th>
                <th>Title</th>
                <th>Status</th>
                <th>SLA Policy</th>
                <th>Resolve Due</th>
                <th>Resolved At</th>
                <th>SLA Breached</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $row)
                <tr>
                    <td><strong>{{ $row['Reference'] }}</strong></td>
                    <td>{{ substr($row['Title'], 0, 40) }}{{ strlen($row['Title']) > 40 ? '...' : '' }}</td>
                    <td>{{ str_replace('_', ' ', $row['Status']) }}</td>
                    <td>{{ $row['SLA Policy'] }}</td>
                    <td>{{ $row['Resolve Due'] }}</td>
                    <td>{{ $row['Resolved At'] }}</td>
                    <td class="breached-{{ strtolower($row['SLA Breached']) }}">{{ $row['SLA Breached'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align:center;">No data available for the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by Enterprise Ticket Management System (ETMS) &copy; {{ date('Y') }}
    </div>
</body>
</html>
